version: '3.8'

services:
  app:
    build: .
    container_name: autoskola_app
    ports:
      - "8080:80"         # Мапим порт 80 контейнера на порт 8080 хоста
    volumes:
      - ./:/var/www/html  # Прямо примонтируем наш проект (если хотим live-редактирование)
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: autoskola_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoschool
      # MYSQL_USER: autoschool_user
      # MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - uploads:/var/www/html/public/uploads
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
  uploads: