version: '3.8'

services:
  app:
    build: .
    container_name: autoskola_app
    ports:
      - "8080:80"         # Mapujeme port 80 kontajnera na port 8080 hostiteľa
    volumes:
      - ./:/var/www/html  # Priamo pripojíme náš projekt (ak chceme live úpravy)
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: autoskola_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoschool

    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - uploads:/var/www/html/public/uploads
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
  uploads: